### ISSUE TITLE
Enable adjusting monitor and stream mix outputs

### ISSUE THREAD

**Issue by mattague** [anaisbetts/midi-mixer-wavexlr#6]
Version: 0.5.1

issue/feature request: is it possible to use this plugin to adjust the monitor mix and stream mix levels from wave link?

**Comment by anaisbetts** [comment]
It's not possible at the moment but is possible In General (i.e. Wave Link exposes this feature)

**Comment by fu-raz** [comment]
Ahh I was looking for this as well. I'll see if I can add it in

**Comment by fu-raz** [comment]
So I added this and it works, but it's not my finest work. I added another function to set output volume. It made things unnecessarily complicated to add to the setVolume method. I've also added added a feature that retries connecting to the wavelink websocket after a minute. This should solve the problems when wavelink starts later than midi mixer on boot.

**Comment by fu-raz** [comment]
Added a pull request #7

**Comment by anaisbetts** [comment]
Fixed!
